.\" rd - privilege elevator
.\" Copyright (C) 2022 ArcNyxx
.\" see LICENCE file for licensing information
.TH RD 1 rd\-VERSION
.SH NAME
rd \- privilege elevator
.SH SYNOPSIS
.SY rd
.OP \-c
.OP \-u user
.I command
.YS
.SH DESCRIPTION
.BR rd (1)
is a simple privilege elevation tool.
.BR rd (1)
only allows users in the GROUP group to execute commands as different users.
After verifying authorisation, some environment variables are reset and
.I command
is run.
.PP
.BR rd (1)
provides multiple patches designed to increase program functionality.
.SS rtconf (RTCONF)
Allow the password requirement, if not already disabled by building with
.IR -DNO_PASSWD ,
to be disabled by creating
.IR /etc/rd .
.SS clearenv (CLEARENV)
Allow the
.I -c
option to clear environment variables before running
.IR command .
.SS usermod (USERMOD)
Allow the
.I -u
option followed by
.I user
to execute commands as that user.  The default user remains
.IR root .
.SH EXIT STATUS
.BR rd (1)
returns with the exit status of
.I command
on success or with 127 on failure.
.SH AUTHOR
Written by ArcNyxx.
.SH SEE ALSO
.BR sudo "(1), " su "(1), " doas "(1), " passwd "(5), " shadow "(3), "
.BR crypt (3)
