.\" rd - privilege elevator
.\" Copyright (C) 2022 ArcNyxx
.\" see LICENCE file for licensing information
.TH RD 1 rd\-VERSION
.SH NAME
rd \- privilege elevator
.SH SYNOPSIS
.SY rd
.OP \-c
.OP \-u user
.I command
.YS
.SH DESCRIPTION
.BR rd (1)
is a simple privilege elevation tool.
.BR rd (1)
only allows users in the
.I GROUP
group to execute commands as different users.  After verifying authorisation,
some critical environment variables are reset and
.I command
is run.
.SH OPTIONS
.TP
.B \-c
Clear all environment variables before resetting critical variables.
.TP
.BI \-u\  user
Execute commands as the specified 
.IR user .
Defaults to
.BR root .
.SH FILES
.TP
.I /etc/rd
Executes commands without a password if exists.
.SH EXIT STATUS
.BR rd (1)
returns with the exit status of
.I command
on success or with 127 on failure.
.SH AUTHOR
Written by ArcNyxx.
.SH SEE ALSO
.BR sudo (1),\  su (1),\  doas (1),\  crypt (3),\  passwd (3),\  shadow (3),
.BR passwd (5),\  shadow (5)
